[package]
name = "neptunus-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
raylib-ffi = "5.0.1"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3
